#!/usr/bin/env php
<?php
/**
 * Craft console bootstrap file
 */

use craft\helpers\App;

define('CRAFT_BASE_PATH', __DIR__);
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Composer autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// dotenv
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    $dotenv = new Dotenv\Dotenv(CRAFT_BASE_PATH);
    $dotenv->load();
}

if ($storagePath = App::env('CRAFT_STORAGE_PATH')) {
    define('CRAFT_STORAGE_PATH', $storagePath);
}

if ($keyPath = App::env('LICENSE_KEY_PATH')) {
    define('CRAFT_LICENSE_KEY_PATH', $keyPath);
}

// Manually load environment variables so they're available to the PHP CLI
$envVars = '/opt/elasticbeanstalk/support/envvars';

if (file_exists($envVars) && is_file($envVars)) {
    $contents = file_get_contents($envVars);

    foreach (explode("\n", $contents) as $line) {
        if (empty($line)) {
            continue;
        }

        $parts = explode(' ', $line);
        $newLine = $parts[1];
        $firstEqual = strpos($newLine, '=');
        $name = substr($newLine, 0, $firstEqual);
        $value = substr($newLine, $firstEqual + 1);
        putenv($name . '=' . $value);
    }
}

define('CRAFT_ENVIRONMENT', App::env('CRAFT_ENV') ?: 'prod');

// Craft
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/console.php';
$exitCode = $app->run();
exit($exitCode);
